categories:
  returns:
    - "return"
    - "refund"
    - "exchange"
  technical_support:
    - "issue"
    - "error"
    - "fix"
    - "problem"
  billing:
    - "bill"
    - "payment"
    - "invoice"
    - "charge"
  general:
    - "help"
    - "assist"
    - "support"
