greetings:
  - "hello"
  - "hi"
  - "good morning"
  - "good afternoon"
  - "good evening"
  - "greetings"
  - "hey"
  - "how can I help you?"
  - "how may I assist you today?"
  - "welcome to"
  - "thank you for calling"
  - "this is"
  - "thank you for reaching out."
  - "welcome to our customer support"

closing:
  - "thank you for calling"
  - "have a great day"
  - "goodbye"
  - "take care"
  - "have a nice day"
  - "stay safe"
  - "thank you for choosing"
  - "if you have further questions, feel free to reach out"
  - "we're here if you need any more help"
  - "it was my pleasure assisting you"
  - "let us know if there's anything else we can do for you"
  - "thank you"

disclaimers:
  - "please do not share any sensitive information"
  - "for your security"
  - "avoid disclosing personal information"
  - "avoid disclosing personal information during this call"
  - "your privacy is important to us. do not share confidential details"
  - "returns must be initiated within"
  - "by proceeding with this call, you agree to our terms and conditions"
  - "all calls may be monitored or recorded for quality and training purposes"
  - "we value your privacy and ensure all data is handled securely"
  - "please review our privacy policy on"
  - "call has been recorded"
