pii_patterns:
  credit_card: "\\b(?:\\d{4}[ -]?){3}\\d{4}\\b"
  atm_pin: "\\b\\d{4}\\b"
  email: "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b"
  ssn: "\\b\\d{3}-\\d{2}-\\d{4}\\b"
  ip_address: "\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b"
  bank_account_number: "\\b\\d{9,18}\\b"

custom_badwords:
  - dumb
  - idiot
  - stupid
